apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  credentials: | 
    [default]
    aws_access_key_id = ASIARZROIHKVITLIK4ZD
    aws_secret_access_key = Pfsdy7QozuEHWEhyoZEZj06CO6Sa4aAO++y033Vc
    aws_session_token=FwoGZXIvYXdzEEIaDGWyITqOf0YKKGdZ0SLVATb7rxMyojq9r5o87YTxDJQsGeESwBDCAH2d/YgkpuEx1Z/HZUcrWRZ9GNkhpLrkxeuc3oOaCFwi1OpwY/yvydZCTTKEKUVCsXbJxcBCaQxEJwDjIDbhuQNhBb33NOkF6hjbW7GsbMum0XiX0ZHEeb5it96I2QkXNkn2u7IiDJdbAW64MQnuHWHAO5dkPn9WasqYJz3UKeTJV/jtFGSEIhA5GXEJlVPetPrml0lwGs3CmrWtCWQd4lKLulLc3BoO/3lrmYUzxLVIpF/KIDGwpqL1Tek05Cihs/qZBjItu+UZjVRd2meDGX9h0vTALLULMXhkH+B4sVq22hrO0GyDzIkidnP/0ArP0FUO