apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEFgaDCox01icp6I+j8ZaKSLVAcm2W5zC/noK6B3X245Lxc9bVdvALyZlGqm5a1KowWOv9MG+K0o691xBlUaFUOMjjFJvJyO85Wjm+4y8vSorrrN1+rQjCBOgnezLruapUj3sLmS9HSePZ+PYTaLvYPBGSt+bYO4zhWKHvTU45cwPrnUEao24T4LB+sSpj6xkgbJ0dGNl/eZ9nlS7wpZC47ZoZypP7iELilX+H5CGKAmzPXKX/rGB2hrgFJEHCBckLo5ig3KuiPOdsKY9gvButJyapwWgYZSS9wuXhL2z1YTSuGKI3ECbtyihkv+ZBjItGlN6WNb03IpU7UZQHvU371KwZHHvJzD0N3xOHkyPriY7R1g5GYz8zOFkg9gB